# Generated by Django 5.0.2 on 2024-03-03 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_delete_news_remove_drinks_price_drinks_face_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fastfoods',
            old_name='image',
            new_name='images',
        ),
    ]
