# Generated by Django 5.0.2 on 2024-03-03 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_rename_image_fastfoods_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
